version: '3.3'
services:    
  mariadb_uca:
    image: almuhs/mariadb_uca:v3
    container_name: mariadb_uca
    volumes:
      - 'mariadb_data_uca2:/var/lib/mysql'
    networks:
        - mynet
  simplesamlphp_moodle_uca:
    image: almuhs/simplesamlphp_moodle_uca:v1
    container_name: simplesamlphp_moodle_uca
    ports: 
      - '8083:80'
      - '8446:443'
    volumes:
        - 'moodle_data_uca:/var/www/html/moodle'
        - 'moodledata_data_uca:/var/www/moodledata'
        - 'simplesamlphp_data_uca:/var/simplesamlphp'
    depends_on:
      - mariadb_uca
    networks:
        - mynet
volumes:
  mariadb_data_uca2:
    driver: local
  moodle_data_uca:
    driver: local
  moodledata_data_uca:
    driver: local
  simplesamlphp_data_uca:
    driver: local
networks:
    mynet:
        external: false
