version: '3.3'
services:
  mariadb_upo:
    image: almuhs/mariadb_upo:v2
    container_name: mariadb_upo
    volumes:
      - 'mariadb_data_upo2:/var/lib/mysql'
    networks:
      - mynet
    ports:
      - '3306:3306'
      
  simplesamlphp_moodle_upo:
    container_name: simplesamlphp_moodle_upo
    image: almuhs/simplesamlphp_moodle_upo:v1
    environment:
        - MARIADB_HOST=mariadb_upo
    ports: 
      - '8081:80'
      - '8444:443'
    volumes:
        - 'simplesamlphp_data_upo:/var/simplesamlphp'
    networks:
        - mynet
    depends_on:
        - mariadb_upo
        
volumes:
  mariadb_data_upo2:
    driver: local
  moodle_data_upo:
    driver: local
  moodledata_data_upo:
    driver: local
  simplesamlphp_data_upo:
    driver: local
networks:
    mynet:
        external: false

